### ISSUE TITLE
Request for guidance: How to use GPT Lyrics + Text-to-music Accompaniment feature

### ISSUE THREAD

**Issue by jonhal** [NZqian/RapBank#4]
First of all, thank you for creating this amazing project! 

I've been exploring the repository and noticed there's a mention of "2.3. GPT Lyrics + Text-to-music Accompaniment" feature. However, I couldn't find detailed instructions on how to use this specific functionality.

Would you be kind enough to provide:
1. A guide on how to use this feature
2. Any specific requirements or dependencies needed
3. Example commands or parameters to run it
4. Expected input/output format

This would be incredibly helpful for users like me who are interested in experimenting with this feature.

Thank you in advance for your time and assistance!

Best regards

**Comment by NZqian** [comment]
It seems that you are referring to Section 2.3 on our demo page. The input of our model consists of lyrics and accompaniment. Therefore, we have also tested using the lyrics generated by GPT and the music generated by text-to-music (Stable Audio) as inputs. Due to internal restrictions, we are unable to open-source the model. This repository contains rap data and the corresponding processing pipeline we used in our paper. You can try to refer to open-source models with similar structures (such as CosyVoice) to reproduce Freestyler :)

**Comment by jonhal** [comment]
OK~ Thank you for your reply ~~
